### PR TITLE
Add `add` command

### LINKED ISSUE #6: Implement an `add` command
The `add` command will take a TSV file name (e.g. `foo.tsv`) and:

1. add a row to `.cogs/sheet.tsv` for `foo`
2. add the column names `.cogs/field.tsv` if they do not already exist

### PR DESCRIPTION
**Pull request by beckyjackson**
Resolves #6 

Note that the table ID is not added in `sheet.tsv`. This is how we know it hasn't been pushed to the Google Sheet yet. Once it's pushed, it will get an ID.

### `add`

Running `add` will begin tracking a local TSV or CSV table. The table details (path, name/title, and description) get added to `.cogs/sheet.tsv` and all headers are added to `.cogs/field.tsv`, if they do not already exist.

```
cogs add [path] -d "[description]"
```

The `-d`/`--description` is optional.

The table title is created from the path (e.g., `tables/foo.tsv` will be named `foo`). If a table with this title already exists in the project, the task will fail.

This does not add the table to the Google Sheet - use `cogs push` to push all tracked local tables to the project Sheet.

### CODE REVIEW

**Comment by jamesaoverton** [comment]
I was thinking that we could do without a `tables/` subdirectory. We would not allow tracked tables to use one of our reserved names: `config`, `sheet`, `field`, `user`, etc. What do you think?

**Comment by beckyjackson** [comment]
I was just using the `tables/foo.tsv` as an example of how the table title is created, but I can change that text if it's confusing.

**Comment by jamesaoverton** [comment]
Ok, I misunderstood. That's fine.

**Comment by beckyjackson** [comment]
Great! This is ready for review.

**Pull request merged**
