### PR TITLE
Add ignore command

### LINKED ISSUE #108: Consider how to ignore a sheet
Currently, if you `cogs add` two tables and then `cogs push`, the Google Sheet will end up with just two sheets, and all other sheets will be deleted. (Note that you can revert changes using Google Sheets history.)

https://github.com/ontodev/cogs/blob/master/cogs/push.py#L215

Now I have a Google Sheet with a bunch of formulas to summarize data on other sheets. COGS doesn't handle formulas, so I can't `cogs add` this sheet. I don't need a local copy of this sheet at all. But I don't want COGS to delete this sheet when I `cogs push`. I'd be happy if COGS just ignored it.

It would be simple enough to provide a list to `clear_remote_sheets` that it would ignore. Then I guess we could use the same list to ignore sheets for `cogs fetch` and `cogs merge` (#102). Maybe we need a new `cogs ignore/unignore` command, or just an `--ignore` option for `cogs add/rm`? And I'm worried that I'm missing other problems, or just making the mental model too complicated.

### PR DESCRIPTION
**Pull request by beckyjackson**
Resolves #108 

This required changes to many of the modules, so I'd like this to be thoroughly tested before merging. I've already tried most of the commands out with an ignored sheet. @jamesaoverton could you try this with your use case?

### CODE REVIEW

**Comment by jamesaoverton** [comment]
This did work for my use case. Thanks! But there are still some design questions that aren't clear to me. I'll add another comment to the issue.

**Comment by jamesaoverton** [comment]
I'd prefer to review this after the other two PRs that I just approved have been merged.

**Comment by beckyjackson** [comment]
OK - the other PRs are merged, and I've updated this to be in sync with `master`

**Comment by jamesaoverton** [comment]
Thanks. This look good, but I want to try it out for real before I mark as approved.

**Review by jamesaoverton — APPROVED** [review]

**Pull request merged**
