### PR TITLE
Add `ls` command

### LINKED ISSUE #36: Implement an `ls` or `list` command
List the currently-tracked sheets for a COGS project.

I'm open to using `ls`, `list`, or some other name.

### PR DESCRIPTION
**Pull request by beckyjackson**
Resolves #36 

Some of the helper functions had unclear names, so I updated these which is why there are changes in multiple files.
* `get_cached()` -> `get_cached_sheets()`
* `get_renamed()` -> `get_renamed_sheets()`
* `get_sheets()` -> `get_tracked_sheets()`

---

### `ls`

Running `ls` displays a list of tracked sheet names and their local paths, even if the local path does not yet exist.

```
cogs ls
```

### CODE REVIEW

**Comment by jamesaoverton** [comment]
`ModuleNotFoundError: No module named 'cogs.ls'`

Please add a basic Travis test to catch that problem.

**Comment by beckyjackson** [comment]
I'm not sure what kind of test would catch that - I think it is a local thing... Did you run `python3 setup.py install`? I also had to remove the egg and install again because `PushError` was removed.

**Comment by jamesaoverton** [comment]
The problem is that the`ls.py` file was not committed. A simple pytest would catch that.

**Comment by beckyjackson** [comment]
Oh - I feel silly now. Thanks, I'll add that in.

**Comment by beckyjackson** [comment]
This is ready now, with a test added.

**Pull request merged**
