### PR TITLE
Fail on pushing with no headers

### LINKED ISSUE #98: Cogs should give a warning when a previously ok table becomes broken
When you try to add a broken table, cogs warns you nicely saying things like "table must have a header". However, when you add/push a good table, and then later break it, you get no such warning (the google sheets just ends up empty). Would be good to get a warning!

### PR DESCRIPTION
**Pull request by beckyjackson**
Resolves #98 

Same error message as trying to `add` with no headers.

### CODE REVIEW

**Comment by jamesaoverton** [comment]
This looks right, but do we also want to check at other times, such as `pull`? I'm not sure.

**Comment by beckyjackson** [comment]
That's a good question... and I don't know. You can `fetch` a sheet without headers just fine, and technically we could update `push` and `add` to be able to handle sheets without headers... Maybe that's the better solution? But I feel like if you're handling a sheet without headers, something is wrong.

**Comment by jamesaoverton** [comment]
We were using headers for the `.cogs/field.tsv` table. Now I think that was a mistake, and I was mixing up my ideas about COGS and VALVE. So I don't think we need `.cogs/field.tsv` in COGS, and we probably don't need COGS to know about the headers at all. What do you think?

**Comment by jamesaoverton** [comment]
We agreed to drop `.cogs/field.tsv`, and then we don't need to check for headers anywhere.

**Comment by beckyjackson** [comment]
Closing in favor of #100

**Pull request closed without merging**
