### PR TITLE
Add the rm function.

### PR DESCRIPTION
**Pull request by bjonnh**
This adds a working (at least in my tests) rm function.

### CODE REVIEW

**Comment by bjonnh** [comment]
This should solve #20.

**Comment by jamesaoverton** [comment]
Looks good to me. @beckyjackson please review, and merge if you agree, or make changes as required.

**Comment by beckyjackson** [comment]
Looks good - the only thing I think would be helpful is an error if you delete _all_ sheets. `gspread`/Google will not let you delete the last remaining sheet from a spreadsheet, so this will throw an error.

**Comment by beckyjackson** [comment]
I'll also update `add` to accept multiple paths, like `rm` does here. 😃

**Comment by bjonnh** [comment]
So what should we do if it is the last sheet? We just refuse to delete it?

**Comment by beckyjackson** [comment]
I think we should check if they are deleting all sheets before doing anything. For example, if there are 3 tracked sheets and they ask to remove all 3, throw an error and don't delete any of them:

```
ERROR: unable to remove X tracked sheet(s) - the spreadsheet must have at least one sheet
```

That way the user can choose which they want to keep, or add a new one and delete the others... Hopefully that makes sense?

**Comment by bjonnh** [comment]
Ok fits what I just pushed, I will update the error message.

**Review by beckyjackson — APPROVED** [review]

**Comment by jamesaoverton** [comment]
I didn't test this yet but the code looks fine and I don't want to block things.

**Pull request merged**
